import {
  app,
  BrowserWindow,
  desktopCapturer,
  ipcMain,
  globalShortcut,
  nativeImage,
  clipboard,
  Tray,
  Menu,
} from "electron";
import * as path from "path";
import { spawn } from "child_process";
import { iconHalf } from "./images";
import dotenv from "dotenv";

dotenv.config();

let pythonProcess: any = null;
let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// start python server and log errors
function startPythonServer() {
  const isDev = process.env.NODE_ENV === "development";

  console.log("isDev:", isDev);
  console.log("__dirname:", __dirname);

  // In development, use the resources directory in project root
  // In production, use the resources directory in app.getAppPath()
  const resourcesPath = isDev
    ? path.join("resources", "python")
    : path.join(process.resourcesPath, "resources", "python");

  console.log("Resources path:", resourcesPath);

  const executableName = process.platform === "win32" ? "server.exe" : "server";
  const pythonExecutable = path.join(resourcesPath, executableName);

  console.log("Starting Python server from:", pythonExecutable);

  pythonProcess = spawn(pythonExecutable);

  pythonProcess.stdout.on("data", (data: any) => {
    console.log("Python server output:", data.toString());
  });

  pythonProcess.stderr.on("data", (data: any) => {
    console.error("Python server error:", data.toString());
  });
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// kill python server and quit app
const handleQuit = () => {
  if (pythonProcess) {
    pythonProcess.kill();
  }
  globalShortcut.unregisterAll();
  if (mainWindow) {
    mainWindow.destroy();
  }
  app.quit();
};

// create window and set up permissions, shortcuts, etc.
const createWindow = (): void => {
  // start python server
  startPythonServer();

  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 900,
    height: 700,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // Set CSP headers to allow connection to localhost:5000
  mainWindow.webContents.session.webRequest.onHeadersReceived(
    (details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            "default-src 'self' 'unsafe-inline' 'unsafe-eval' data:;",
            "connect-src 'self' http://localhost:5001 https://cgkethnnnnsxbzvglfmn.supabase.co;",
            "img-src 'self' data: http://localhost:5001;",
            "script-src 'self' 'unsafe-inline' 'unsafe-eval';",
          ].join(" "),
        },
      });
    }
  );

  // hide menu bar
  mainWindow.setMenuBarVisibility(false);

  // load window content
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Add media permissions
  mainWindow.webContents.session.setPermissionRequestHandler(
    (webContents, permission, callback) => {
      if (permission === "media") {
        callback(true);
      } else {
        callback(false);
      }
    }
  );

  // Add these permissions for screen capture
  mainWindow.webContents.session.setPermissionCheckHandler(
    (webContents, permission) => {
      if (permission === "media") {
        return true;
      }
      return false;
    }
  );

  // close window
  mainWindow.on("close", (event) => {
    // TODO: check if this keeps app from going to tray on macos
    if (process.platform === "darwin") {
      mainWindow.close();
    } else {
      event.preventDefault();
      mainWindow.hide();
    }
  });

  // Register global shortcut
  globalShortcut.register("CommandOrControl+Shift+Alt+S", () => {
    mainWindow.webContents.send("trigger-screenshot");
  });

  // Open the DevTools.
  if (process.env.NODE_ENV === "development") {
    mainWindow.webContents.openDevTools();
  }

  // Send available screen sources to React
  ipcMain.handle("get-sources", async () => {
    const sources = await desktopCapturer.getSources({
      types: ["screen", "window"],
      thumbnailSize: { width: 320, height: 240 },
    });

    return sources.map((source) => ({
      id: source.id,
      name: source.name,
      thumbnail: source.thumbnail.toDataURL(),
    }));
  });

  // capture screenshot of window or screen
  ipcMain.handle("capture-source", async (_, sourceId) => {
    const sources = await desktopCapturer.getSources({
      types: ["screen", "window"],
    });
    const source = sources.find((src) => src.id === sourceId);

    if (!source) {
      console.error("Source not found!");
      return null;
    }

    // Get full-resolution image using getUserMedia
    return new Promise((resolve) => {
      navigator.mediaDevices
        .getUserMedia({
          audio: false,
          video: {
            mandatory: {
              chromeMediaSource: "desktop",
              chromeMediaSourceId: source.id,
              minWidth: 1920, // Adjust width
              minHeight: 1080, // Adjust height
              maxWidth: 3840, // High-resolution limit
              maxHeight: 2160,
              maxFrameRate: 1,
            },
          } as any,
        })
        .then((stream) => {
          const video = document.createElement("video");
          video.srcObject = stream;
          video.onloadedmetadata = () => {
            video.play();
            setTimeout(() => {
              const canvas = document.createElement("canvas");
              canvas.width = video.videoWidth;
              canvas.height = video.videoHeight;
              const ctx = canvas.getContext("2d");
              ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
              stream.getTracks().forEach((track) => track.stop());
              resolve(canvas.toDataURL("image/png"));
            }, 500);
          };
        })
        .catch((err) => {
          console.error("Failed to capture screen:", err);
          resolve(null);
        });
    });
  });

  // get os
  ipcMain.handle("get-os", () => {
    return process.platform;
  });

  // Add IPC handler for clipboard
  ipcMain.handle("copy-to-clipboard", async (_, dataUrl: string) => {
    try {
      const image = nativeImage.createFromDataURL(dataUrl);
      clipboard.writeImage(image);
      return true;
    } catch (error) {
      console.error("Failed to copy to clipboard:", error);
      return false;
    }
  });

  // focus window
  ipcMain.handle("focus-window", () => {
    if (mainWindow) {
      mainWindow.show();
      mainWindow.focus();
    }
  });

  // Add IPC handler for getting environment variables
  ipcMain.handle("get-env", (_, key: string) => {
    return process.env[key];
  });

  ipcMain.handle("minimize-window", () => {
    if (mainWindow) {
      mainWindow.minimize();
    }
  });

  // set tray
  app.whenReady().then(() => {
    tray = new Tray(path.join(__dirname, iconHalf));
    const contextMenu = Menu.buildFromTemplate([
      {
        label: "Show",
        type: "normal",
        click: () => {
          if (mainWindow) {
            mainWindow.show();
            mainWindow.focus();
          }
        },
      },
      { label: "Quit", type: "normal", click: handleQuit },
    ]);
    tray.setToolTip("PixelSnag");
    tray.setContextMenu(contextMenu);

    // Add click handler for the tray icon
    tray.on("click", () => {
      if (mainWindow) {
        mainWindow.show();
        mainWindow.focus();
      }
    });
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    handleQuit();
  }
});

// create new window if none are open
app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Ensure handleQuit is called when the app is about to quit
app.on("before-quit", handleQuit);
